version: "3"

services:
  libvirtd:
    build: .
    image: "silvermindlabs/libvirt"
    privileged: true
    # command: bash -c 'while true; do echo; sleep 1000; done;'
    volumes:
      - .:/root/libvirt/:Z
    network_mode: host
    # ipc: host
    # pid: host
    # user: root
